apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-nfs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce #ReadWriteOnce RWO (1:1 마운트, 읽기 쓰기)
  nfs:
    path: /nfs-wp #NFS 저장소
    server: 192.168.10.100 #NFS-Server의 IP
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-nfs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /nfs-mysql
    server: 192.168.10.100
