AWSTemplateFormatVersion: 2010-09-09
Description: Make a VPC 1

#-------------------------------
# VPC, InternetGateway, Subnet,RouteTable
#-------------------------------
Resources:
  TutorialVPC: ## VPC
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 172.0.0.0/16 #VPC의 기본 IPv4 CIDR 블록
      EnableDnsHostnames: true #VPC에서 시작된 인스턴스가 DNS 호스트 이름을 가져오는지 여부를 나타냄
  ## InternetGateway
  InternetGateway:
    Type: AWS::EC2::InternetGateway
  ##인터넷 게이트웨이와 VPC를 연결
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref TutorialVPC
      InternetGatewayId: !Ref InternetGateway

  ## Public Subnet
  PublicSubnet01:
    Type: AWS::EC2::Subnet #VPC의 서브넷을 지정
    Properties:
      VpcId: !Ref TutorialVPC #서브넷이 있는 VPC의 ID. "VPCId: 참조하려는 리소스 또는 매개변수의 이름"(=>참조한 후 매개변수 또는 리소스의 값을 반환)
      CidrBlock: 172.0.0.0/24 #서브넷에 할당된 IPv4 CIDR 블록
      AvailabilityZone: !Select #이 서브넷의 가용 영역.
        - '0'
        - !GetAZs ''
  ##PrivateSubnet
  PrivateSubnet01:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref TutorialVPC
      CidrBlock: 172.0.1.0/24
      AvailabilityZone: !Select
        - '0'
        - !GetAZs ''
  #Route Table
  PublicRouteTable:
    Type: AWS::EC2::RouteTable #Route Table만들고
    Properties:
      VpcId: !Ref TutorialVPC

  PublicRoute:
    Type: AWS::EC2::Route #Routing Table 설정하고
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnetRouteTableAssociation1:
    Type: AWS::EC2::SubnetRouteTableAssociation #서브넷 연결
    Properties:
      SubnetId: !Ref PublicSubnet01
      RouteTableId: !Ref PublicRouteTable

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref TutorialVPC

  #PrivateRoute는 필요없으니까 생략#
  PrivateSubnetRouteTableAssociation1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet01
      RouteTableId: !Ref PrivateRouteTable
Outputs:
  VPC:
    Description: Tutorial VPC ID
    Value: !Ref TutorialVPC
  AZ1:
    Description: Availability Zone 1
    Value: !GetAtt
      - PublicSubnet01
      - AvailabilityZone
